    
modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Turkey2349/A-Block-Of-Flint/issues"
[[mods]]
    modId="flintblock"
    version="1.0"
    displayName="A Block of Flint"
    displayURL="https://minecraft.curseforge.com/projects/a-block-of-flint"
    authors="Turkey2349"
    description='''
    What do you think it does?
    '''
    [[dependencies.examplemod]]
        modId="forge"
        mandatory=true
        versionRange="[25,)"
        ordering="NONE"
        side="BOTH"