    
modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/TheTurkeyDev/A-Block-Of-Flint/issues"
displayURL="https://minecraft.curseforge.com/projects/a-block-of-flint"
authors="TurkeyDev"
license="MIT"
[[mods]]
    modId="flintblock"
    version="1.2"
    displayName="A Block of Flint"
    description='''
    What do you think it does?
    '''